# Generated by Django 4.1 on 2022-08-16 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invest',
            fields=[
                ('id_invest', models.AutoField(primary_key=True, serialize=False)),
                ('invest_type', models.CharField(max_length=150, verbose_name='Tipo de Investimento')),
                ('investor', models.CharField(max_length=150, verbose_name='Investidor')),
                ('created_at', models.DateField(blank=True, null=True, verbose_name='Data do Investimento')),
                ('value_invest', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do Investimento')),
            ],
        ),
    ]
